export const avatar = 'https://i.ibb.co/WWhZDRM/avatar.png';

export const data = [
  {
    id: 'bd7a8afc-3da1-4c40-9d77-6a1e09cbd109',
    title: 'Klever Tasks',
    total: 10,
    current: 1,
    description: 'Add all pending task in order to publish the app',
    category: 'Development',
  },
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
    title: 'Grocery Shopping',
    total: 20,
    current: 5,
    description: 'Shopping for groceries',
    category: 'Shopping',
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
    title: 'Fitness Goals',
    total: 30,
    current: 10,
    description: 'Achieving fitness milestones',
    category: 'Health',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e29d72',
    title: 'Home Improvement But With Class Another Clip',
    total: 100,
    current: 99,
    description: 'Renovating and decorating home',
    category: 'Home',
  },
  {
    id: '4d9c141d-6de3-4c40-96e2-fc5fa8a5b602',
    title: 'Learning New Language',
    total: 25,
    current: 25,
    description: 'Mastering a new language',
    category: 'Education',
  },
  {
    id: '7cf5e99e-7388-4e2e-9d77-fdb26a05f05e',
    title: 'Travel Adventures',
    total: 40,
    current: 15,
    description: 'Exploring new destinations',
    category: 'Travel',
  },
  {
    id: 'e3b87d1f-1868-492f-aa49-6a1e1b35a5e4',
    title: 'Cooking Class',
    total: 10,
    current: 2,
    description: 'Attending a cooking workshop',
    category: 'Food',
  },
  {
    id: 'aab96c46-78d4-4d70-9e2a-d0c209cb9b0a',
    title: 'DIY Project',
    total: 35,
    current: 18,
    description: 'Building furniture for the house',
    category: 'Home',
  },
  {
    id: 'cad7d3bc-b29b-4e35-9f6b-20796be5d109',
    title: 'Coding Challenge',
    total: 50,
    current: 35,
    description: 'Completing coding challenges on LeetCode',
    category: 'Technology',
  },
  {
    id: '4ae8fd7b-ba33-4e52-83c2-03cb38be2284',
    title: 'Guitar Practice',
    total: 20,
    current: 12,
    description: 'Learning new songs on the guitar',
    category: 'Music',
  },
  {
    id: '5f7f394b-6202-4be5-b676-c46e49b460e1',
    title: 'Reading Challenge',
    total: 15,
    current: 7,
    description: 'Reading books from different genres',
    category: 'Literature',
  },
];


export const defaultItem = [
  { label: 'Manzana', isChecked: true },
  { label: 'Banana', isChecked: true },
  { label: 'Uva', isChecked: true },
  { label: 'Cereza', isChecked: true },
  { label: 'Naranja', isChecked: false },
  { label: 'Melón', isChecked: true },
  { label: 'Sandía', isChecked: false },
  { label: 'Piña', isChecked: true },
  { label: 'Durazno', isChecked: false },
  { label: 'Pera', isChecked: false },
  { label: 'Papaya', isChecked: true },
  { label: 'Fresa', isChecked: false },
  { label: 'Mango', isChecked: false },
  { label: 'Kiwi', isChecked: false },
  { label: 'Limón', isChecked: true },
];

type ObjectWithNestedObjects = {
  [key: string]: {
    label: string;
    isChecked: boolean;
  }[]
};

export const items: ObjectWithNestedObjects = {
  'bd7a8afc-3da1-4c40-9d77-6a1e09cbd109': [
    { label: 'Add Modal to Cards', isChecked: false },
    { label: 'Add new cards to home page', isChecked: false },
    { label: 'Add translation function (EN-ES-IT?)', isChecked: false },
    { label: 'Add a new screen to see all lists', isChecked: false },
    { label: 'Add toogle functionality to Items', isChecked: false },
    { label: 'Add new items to list (at least by local method)', isChecked: false },
    { label: 'Add Voice feature', isChecked: false },
    { label: 'Create home top component (idk what)', isChecked: false },
    { label: 'Add the posibility to see a short description somewhere', isChecked: false },
    { label: 'Add a menu to see list all completed lists (hide in home)', isChecked: false },
    { label: 'Avoid go back on Home screen', isChecked: false },
    { label: 'Connect with Firebase or an external DB', isChecked: false },
    { label: 'Connect with Google', isChecked: false },
    { label: 'Connect with Facebook', isChecked: false },
  ],
  'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba': [
    { label: 'Milk', isChecked: true },
    { label: 'Bread', isChecked: true },
    { label: 'Eggs', isChecked: true },
    { label: 'Rice', isChecked: true },
    { label: 'Pasta', isChecked: false },
    { label: 'Chicken', isChecked: true },
    { label: 'Vegetables', isChecked: false },
    { label: 'Fruits', isChecked: true },
    { label: 'Cereal', isChecked: false },
    { label: 'Yogurt', isChecked: false },
    { label: 'Cheese', isChecked: true },
    { label: 'Coffee', isChecked: false },
    { label: 'Tea', isChecked: false },
    { label: 'Water', isChecked: false },
    { label: 'Sodas', isChecked: true },
    { label: 'Cookies', isChecked: true },
    { label: 'Snacks', isChecked: false },
    { label: 'Sauce', isChecked: false },
    { label: 'Spices', isChecked: false },
    { label: 'Oil', isChecked: true }
  ],
  '3ac68afc-c605-48d3-a4f8-fbd91aa97f63': [
    { label: 'Towel', isChecked: true },
    { label: 'Water Bottle', isChecked: true },
    { label: 'Sneakers', isChecked: true },
    { label: 'Sportswear', isChecked: true },
    { label: 'Lock', isChecked: false },
    { label: 'Gloves', isChecked: true },
    { label: 'Music', isChecked: false },
    { label: 'Weights', isChecked: true },
    { label: 'Mat', isChecked: false },
    { label: 'Sports Watch', isChecked: false },
    { label: 'Bar', isChecked: true },
    { label: 'Rope', isChecked: false },
    { label: 'Measuring Tape', isChecked: false },
    { label: 'Cap', isChecked: false },
    { label: 'Supplements', isChecked: true },
    { label: 'Trainer', isChecked: true },
    { label: 'Class', isChecked: false },
    { label: 'Cardio', isChecked: false },
    { label: 'Exercise', isChecked: false },
    { label: 'Progress', isChecked: true }
  ],
  '58694a0f-3da1-471f-bd96-145571e29d72': defaultItem,
  '4d9c141d-6de3-4c40-96e2-fc5fa8a5b602': [
    { label: 'Math Book', isChecked: true },
    { label: 'Notebooks', isChecked: true },
    { label: 'Pencils', isChecked: true },
    { label: 'Markers', isChecked: true },
    { label: 'Calculator', isChecked: false },
    { label: 'Backpack', isChecked: true },
    { label: 'Ruler', isChecked: false },
    { label: 'Eraser', isChecked: true },
    { label: 'Scissors', isChecked: false },
    { label: 'Glue', isChecked: false },
    { label: 'History Book', isChecked: true },
    { label: 'Dictionary', isChecked: false },
    { label: 'Uniform', isChecked: false },
    { label: 'Water Bottle', isChecked: false },
    { label: 'Snack', isChecked: true },
    { label: 'Project', isChecked: true },
    { label: 'Exam', isChecked: false },
    { label: 'Extracurricular Activities', isChecked: false },
    { label: 'Paper', isChecked: false },
    { label: 'Laptop', isChecked: true }
  ],
  '7cf5e99e-7388-4e2e-9d77-fdb26a05f05e': defaultItem,
  'e3b87d1f-1868-492f-aa49-6a1e1b35a5e4': [
    { label: 'Prepare ingredients for dinner', isChecked: true },
    { label: 'Bake cookies for dessert', isChecked: false },
    { label: 'Chop vegetables for salad', isChecked: false },
    { label: 'Make grocery list for the week', isChecked: true },
    { label: 'Clean kitchen countertops', isChecked: true },
    { label: 'Organize spice rack', isChecked: false },
    { label: 'Try out a new recipe', isChecked: true },
    { label: 'Research cooking techniques online', isChecked: false },
    { label: 'Plan meals for the upcoming week', isChecked: true },
    { label: 'Restock pantry staples', isChecked: false },
    { label: 'Experiment with different spices', isChecked: false },
    { label: 'Create a meal prep schedule', isChecked: true },
    { label: 'Clean and organize refrigerator', isChecked: false },
    { label: 'Make homemade pasta sauce', isChecked: true },
    { label: 'Attend a cooking class', isChecked: false },
    { label: 'Cook a family dinner', isChecked: false },
    { label: 'Learn to bake bread from scratch', isChecked: false },
    { label: 'Host a dinner party', isChecked: true },
    { label: 'Practice knife skills', isChecked: true }
  ],
  'aab96c46-78d4-4d70-9e2a-d0c209cb9b0a': [
    { label: 'Set project goals', isChecked: true },
    { label: 'Create project timeline', isChecked: true },
    { label: 'This is a long item label for testing porpuse so I dont know how to manage', isChecked: false },
    { label: '12345678912345678912345678912345678912345678912345', isChecked: false },
    { label: 'Assign tasks to team members', isChecked: false },
    { label: 'Conduct research for the project', isChecked: true },
    { label: 'Develop project proposal', isChecked: true },
    { label: 'Hold project kickoff meeting', isChecked: false },
    { label: 'Gather project requirements', isChecked: true },
    { label: 'Define project scope', isChecked: false },
    { label: 'Design project plan', isChecked: true },
    { label: 'Review project budget', isChecked: false },
    { label: 'Monitor project progress', isChecked: true },
    { label: 'Communicate with stakeholders', isChecked: true },
    { label: 'Address project risks', isChecked: false },
    { label: 'Document project milestones', isChecked: true },
    { label: 'Review project outcomes', isChecked: false },
    { label: 'Prepare project presentation', isChecked: true },
    { label: 'Celebrate project completion', isChecked: false },
    { label: 'Update project documentation', isChecked: true },
    { label: 'Conduct project retrospective', isChecked: true },
    { label: 'Plan for future projects', isChecked: false }
  ],  
  'cad7d3bc-b29b-4e35-9f6b-20796be5d109': [
    { label: 'Laptop', isChecked: true },
    { label: 'Phone', isChecked: true },
    { label: 'Documents', isChecked: true },
    { label: 'Pen', isChecked: true },
    { label: 'Notebook', isChecked: false },
    { label: 'Coffee', isChecked: true },
    { label: 'Agenda', isChecked: false },
    { label: 'Contract', isChecked: true },
    { label: 'Presentation', isChecked: false },
    { label: 'Report', isChecked: false },
    { label: 'Meeting', isChecked: true },
    { label: 'Email', isChecked: false },
    { label: 'Invoice', isChecked: false },
    { label: 'Budget', isChecked: false },
    { label: 'Project', isChecked: true },
    { label: 'Clients', isChecked: true },
    { label: 'Team', isChecked: false },
    { label: 'Boss', isChecked: false },
    { label: 'Employee', isChecked: false },
    { label: 'Schedule', isChecked: true }
  ],
  '4ae8fd7b-ba33-4e52-83c2-03cb38be2284': [
    { label: 'Practice scales for 30 minutes', isChecked: true },
    { label: 'Learn new chords: G, C, D', isChecked: true },
    { label: 'Practice chord transitions', isChecked: false },
    { label: 'Work on fingerpicking techniques', isChecked: true },
    { label: 'Review previous lesson notes', isChecked: false },
    { label: 'Watch guitar tutorial videos online', isChecked: true },
    { label: 'Experiment with different strumming patterns', isChecked: false },
    { label: 'Practice playing along with a metronome', isChecked: true },
    { label: 'Improvise and jam over backing tracks', isChecked: false },
    { label: 'Record practice sessions for self-evaluation', isChecked: true },
    { label: 'Learn music theory concepts: major/minor scales', isChecked: true },
    { label: 'Work on barre chord techniques', isChecked: false },
    { label: 'Explore different guitar styles: blues, rock, folk', isChecked: true },
    { label: 'Attend a guitar workshop or masterclass', isChecked: false },
    { label: 'Practice ear training and recognizing intervals', isChecked: true },
    { label: 'Set specific practice goals for the week', isChecked: true },
    { label: 'Transcribe a song by ear', isChecked: false },
    { label: 'Experiment with guitar effects and pedals', isChecked: true },
    { label: 'Play in front of friends or family for feedback', isChecked: false }
  ],  
  '5f7f394b-6202-4be5-b676-c46e49b460e1': [
    { label: 'To Kill a Mockingbird', isChecked: true },
    { label: '1984', isChecked: true },
    { label: 'The Great Gatsby', isChecked: true },
    { label: 'Pride and Prejudice', isChecked: false },
    { label: 'The Catcher in the Rye', isChecked: true },
    { label: 'The Lord of the Rings', isChecked: true },
    { label: 'Harry Potter Series', isChecked: false },
    { label: 'The Chronicles of Narnia', isChecked: true },
    { label: 'The Hobbit', isChecked: false },
    { label: 'Animal Farm', isChecked: true }
  ],
}